### ISSUE TITLE
Make class mappings first, before field mappingsss

### ISSUE THREAD

**Issue by PizzaCrust** [chibill/Minecraft-Mappings#1]

**Comment by wgaylord** [comment]
?
The field mappings at the top are auto generated the way they are and they made the enum constants.

**Comment by PizzaCrust** [comment]
coool what do you use to autogenerate

**Comment by wgaylord** [comment]
Which part? The enum constants are generated using a slightly modified
version of a tool Carbon (1.11 snapshot stuff in spigot 1.10) was using.
They are up on my server. For basically every version of MC.

**Comment by PizzaCrust** [comment]
clazz

**Comment by wgaylord** [comment]
I use my https://minecraft16.ml/minecraft/jar_fingerprints/ along with constant data extracted from a fingerprint of a remapped 1.11. Also I follow the classes supers to place classes in close to the correct package. I should open source that code. But it is still buggy and I really don't like releasing super buggy stuff. Plus nothing is documented.

**Comment by wgaylord** [comment]
Question is this still valid? (The emun mappings are literally prepended to the file.)
