### ISSUE TITLE
Some classes not mapped.

### ISSUE THREAD

**Issue by pisaiah** [chibill/Minecraft-Mappings#3]
When using the latest 1.12-pre5 mappings, they don't map some server classes.

**Comment by wgaylord** [comment]
That's because they are not full mapping..

Like I have said.

**Comment by pisaiah** [comment]
could you update them?

**Comment by wgaylord** [comment]
I could but why? I have just been uploading my automatically generated ones.

**Comment by pisaiah** [comment]
They are only 90% usable. Some mods fail compiling.

**Comment by wgaylord** [comment]
They are not meant to run mods right away.... like I said they are just ones I can automatically generate. With out ever touching the mappings. 

Plus the mods fail because only classes are mapped.  Listen.

**Comment by wgaylord** [comment]
@IsaiahPatton what mods did you try just interested.

**Comment by pisaiah** [comment]
github.com/Project-Rails/ProjectRails
It's a minecraft server mod.

**Comment by wgaylord** [comment]
Well the reason this will never build with my mappings is because of me not making method or field mappings yet.

**Comment by pisaiah** [comment]
Isn't this part of the fields? https://github.com/chibill/Minecraft-Mappings/blob/master/1.12/1.12-pre2.srg#L9

**Comment by wgaylord** [comment]
Sort of these are the enum constants. Which are technically fields.
Those I am also able to generate automatically with out touching the stuff myself.

Also you could just hop on IRC to talk...
